pipeline {
    agent any
    options {
        buildDiscarder(logRotator(daysToKeepStr: '5', artifactDaysToKeepStr: '5', numToKeepStr: '5'))
        timestamps()
    }

    environment {
        WORKSPACE_DIR = "${env.WORKSPACE}"
    }

    stages {
        stage('Build and Use Image 1') {
            agent {
                dockerfile {
                    filename "first.Dockerfile"
                    additionalBuildArgs '--build-arg WORKSPACE=/workspace'
                    args "-v ${env.WORKSPACE}:/workspace"
                }
            }
            steps {
                sh 'echo "This is some content" > /workspace/shared_file.txt'
                sh 'echo "File created in container 1"'
            }
        }

        stage('Build and Use Image 2') {
            agent {
                dockerfile {
                    filename "second.Dockerfile"
                    additionalBuildArgs '--build-arg WORKSPACE=/workspace'
                    args "-v ${env.WORKSPACE}:/workspace"
                }
            }
            steps {
                sh 'cat /workspace/shared_file.txt'
                sh 'echo "File contents printed from container 2"'
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'shared_file.txt',
                             allowEmptyArchive: true,
                             fingerprint: true,
                             onlyIfSuccessful: true
            cleanWs()
        }
        failure {
            script {
                // CHANGE_ID is set only for pull requests, so it is safe to access the pullRequest global variable
                if (env.CHANGE_ID) {
                    pullRequest.addLabel('Build Failed')
                }
            }
        }
    }
}
